update readme
OpenCSGs/csghub pull request #724
Opened 2024-10-18 07:11 UTC by kayla050

**What this PR does**:
Update Readme file.
**Which issue(s) this PR fixes**:

Fixes #

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevant result summary. 

- [ ] Test A
- [ ] Test B

- Logs

**Special notes for your reviewer**:

**Checklist**:

- [x] I have added unit/e2e tests that prove your fix is effective or that this feature works.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have reviewed my own code and ensured that it follows the project's style guidelines.

**Release note**:

```release-note

```

2024-10-18 07:12 UTC, kayla050 commented
@jasonhe258 pls take a look this readme file, thx.

2024-10-18 07:41 UTC, jasonhe258 commented on README.md
> +- For those looking to explore, experiment with CSGHub's free SaaS version on the [OpenCSG website](https://opencsg.com/models). Refer to this [brief quick start guide](https://opencsg.com/docs/en/in
Better to change to "For those looking to quickly explore"?

2024-10-18 07:43 UTC, jasonhe258 commented on README_zh.md
> +**[简体中文](README_zh.md) ∙ [日本語](README_jp.md) ∙ [한국어](README_kr.md)**
English version link should be shown here, instead of Chinese, due to this is Chinese version.

2024-10-18 07:47 UTC, jasonhe258 commented
@kayla050 Thanks for your great contribution! Looks good to me beside of a few minor issues.

2024-10-18 07:48 UTC, jasonhe258 commented on README_zh.md
> +**[简体中文](README_zh.md) ∙ [日本語](README_jp.md) ∙ [한국어](README_kr.md)**
Please also update other lang's Readme. Thanks.

2024-10-18 07:51 UTC, jasonhe258 commented
By the way, personally I think we can add a E2E quick guide for CSGHub beginner.

2024-10-20 12:05 UTC, jasonhe258 commented
@kayla050 LGTM. Thanks for your great contribution again!

@Rader Would you please take a look again? Thanks.

2024-10-23 03:08 UTC, Rader requested changes

2024-10-23 03:08 UTC, Rader commented on docs/release_notes_zh.md
> +  `CSGHub` 门户迁移至 Go 版本，git 服务器支持 Gitaly 并默认启用；新增了“合集”功能、资源控制台页面；运行空间的终端微调不再需要域名；此外，还进行了其他用户体验优化和错误修复。
运行空间的终端微调 -》 应用空间、模型推理和微调实例的运行

2024-10-23 03:08 UTC, Rader commented on docs/release_notes_zh.md
> +  重要版本更新，支持“专用”模型推理终端；支持 `streamlit` 空间；允许用户`收藏`仓库并为仓库设置`行业标签`；增强 git 历史和提交差异详情展示。
支持“专用”模型推理终端 -> 支持“专属”模型推理实例

2024-10-23 03:08 UTC, Rader commented on docs/release_notes_zh.md
> +  提升空间的用户体验；自动建立仓库之间（模型、数据集、代码和空间）的“关系”；支持多文件上传。
空间 -》 应用空间

2024-10-23 05:42 UTC, kayla050 commented
@Rader Modified readme, csghub saas guide and release note with your comments. Could you please review it again? Thanks!

2024-10-23 06:21 UTC, Rader approved these changes

2024-10-23 11:39 UTC, hiveer approved these changes

2024-10-23 12:56 UTC, merged